### ISSUE TITLE
clone issue

### ISSUE THREAD

**Issue by kenna3** [ps1337/jka-multihack#1]
hi when i try to clone the repository it just gives some errors about some files not being able to clone bots.lib and few others and then i cant build the solution

**Comment by ps1337** [comment]
It works for me. Also, there's no boot.lib file in the repo. Just download the zip 



-----Original Message-----

**Comment by kenna3** [comment]
ok which file do i load to visual studio to build it or could u build i and sen d me to hotmail please

**Comment by kenna3** [comment]
- 
![unknown](https://user-images.githubusercontent.com/78531150/106867186-35139b80-66c5-11eb-9ec8-4b9e42afefd7.png)

**Comment by ps1337** [comment]
the dll and loader are two separate binaries, so you'll have to create and compile two things
